### ISSUE TITLE
How to get executable file by "make" instead of "make install"

### ISSUE THREAD

**Issue by Lee-Marry** [ksnip/kImageAnnotator#255]
Hi, Glad to read your source code,when I run the project, I find that get the executable file by "make" instead of "make install" will be better, so can you tell me how to get executable file by "make" instead of "make install".Appreciate it.

**Comment by DamirPorobic** [comment]
Hi there, for what executable are you looking? kImageAnnoator is a library so it won't execute on it own and doesn't have an executable. If you are looking for the library and have followed this instruction https://github.com/ksnip/kImageAnnotator#building-from-source the it should be under `./build/lib`. If you are looking for the example application, that one should be under `./build/example`

**Comment by DamirPorobic** [comment]
Closing this one as it's stale. Feel free to reopen if you have further questions.

**Comment by tonymurray** [comment]
Hello, I was hoping to test the latest version 2022 with crop - then integrated into Spectacle. I successfully built from source and the example application works. 

What would be the step to integrate the newer version with Spectacle (if that is possible). 

I tried target_link_libraries(spectacle kImageAnnotator) -- but there was an error - perhaps needs to be executed in a certain  folder?

**Comment by DamirPorobic** [comment]
Did you install it? kImageAnnotator needs to be installed in order for Spectale build to find it. I don't think that you need change anything in the Spectacle cmake config, it should find any installed kImageAnnotator instance and use it, the `target_link_libraries(spectacle kImageAnnotator)` should be in there somewhere already. Thought I'm not a expert in Spectacle.

**Comment by tonymurray** [comment]
I did the sudo make install step - I assumed this would install it. 

I tried uninstalled spectacle and reinstalled.
It installs kImageAnnotator version 0.5.3-1 as a dependency. (Otherwise will not install)

In /usr/lib:

libkImageAnnotator.so -> libkImageAnnotator.so.0
libkImageAnnotator.so.0 -> libkImageAnnotator.so.0.5.3
libkImageAnnotator.so.0.5.3

In /usr/local/lib:
libkImageAnnotator.so -> libkImageAnnotator.so.0
libkImageAnnotator.so.0 -> libkImageAnnotator.so.0.6.0
libkImageAnnotator.so.0.6.0


I tried 
export LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib

In /usr/bin:
ldd spectacle | grep kImage
libkImageAnnotator.so.0 => /lib/libkImageAnnotator.so.0

Trying to find a way for spectacle to find the version in /usr/local/lib -- 
Guess I could try changing the links in /usr/lib, but there is probably a better way to do it?

**Comment by ernstki** [comment]
> Hi, Glad to read your source code,when I run the project, I find that get the executable file by "make" instead of "make install" will be better, so can you tell me how to get executable file by "make" instead of "make install".Appreciate it.

@Lee-Marry The `make` and `make install` steps are separate by long-standing convention. One simply builds the libraries and binaries, the other (which usually requires you to become the root user, _e.g._, with `sudo`) installs them to the filesystem for everyone to use, typically to `/usr/local/`.

If your _real_ question is how to install without becoming root, assuming you have all other prerequisites in place (including [kColorPicker](https://github.com/ksnip/kColorPicker)), this may work for you:

```bash
git clone https://github.com/ksnip/kImageAnnotator.git
cd kImageAnnotator
mkdir build && cd build
cmake -D CMAKE_INSTALL_PREFIX=~/.local ..
make && make install
```

See #959 for more details.

Most distros will add `~/.local/bin` to your path upon login, assuming the path already exists. If it doesn't work at first, try logging out and back in. If you're still having trouble, then that's beyond the scope of this issue, and I'd encourage you to ask for further help in your favorite chat room, forum, or Q&A site.
